[package]
name = "pdf2text"
version = "0.1.0-dev"
edition = "2024"
license = "MIT-0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
pdf-extract = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
